unclassified:
  jenkins.model.GlobalJobDslSecurityConfiguration:
    useScriptSecurity: true
    inScriptApproval:
      - "method groovy.json.JsonOutput toJson java.util.LinkedHashMap"
      - "new groovy.json.JsonSlurper"
      - "method groovy.json.JsonSlurper parseText java.lang.String"
  hudson.plugins.jobConfigHistory.GlobalJobConfigHistory:
    enableGlobalConfigFiles: true
jobs:
  - script: >
      freeStyleJob('MyCloudJob') {
          description('This is my job')
          steps {
              // Define your build steps here
          }
          wrappers {
              // Define your wrappers here
          }
          publishers {
              // Define your publishers here
          }
          properties {
              // Define any job properties here
          }
          triggers {
              // Define any job triggers here
          }
          concurrentBuild(false)
          cloud('MyCloud') {
              labelString('newECSagent') // Specify your cloud label here
          }
      }












